services:
  backend-api:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network

  frontend-react:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge