apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microshop
data:
  USER_SERVICE_URL: "http://account-service:3001"
  PRODUCT_SERVICE_URL: "http://product-service:3002"
  MONGO_URI: "mongodb://root:password@mongo:27017/productdb?authSource=admin"
  DATABASE_URL: "postgresql://user:password@postgres:5432/shop_db_k8s"
  REACT_APP_API_URL: ""
  NODE_ENV: "production"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: microshop
data:
  POSTGRES_DB: "shop_db"
  MONGO_INITDB_DATABASE: "productdb"