apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: microshop
spec:
  selector:
    app: product-service
  ports:
    - port: 3002
      targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: microshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              "until nc -z mongo 27017; do echo 'Waiting for MongoDB...'; sleep 2; done; echo 'MongoDB is ready!'",
            ]
      containers:
        - name: product-service
          image: product-service:latest
          imagePullPolicy: Never 
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: MONGO_URI
              value: "mongodb://root:password@mongo:27017/productdb?authSource=admin"