services:
  frontend-react:
    build:
      context: ../../services/frontend-react
      dockerfile: Dockerfile 
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped

  api-gateway:
    build:
      context: ../../services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: unless-stopped

  account-service:
    build:
      context: ../../services/account-service
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine 
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=user 
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shop_db 
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: