services:
  api-gateway:
    build:
      context: ../../services/api-gateway
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ../../services/api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  account-service:
    build:
      context: ../../services/account-service
      target: development
    env_file:
      - ../../services/account-service/.env
    ports:
      - "3001:3001"
    volumes:
      - ../../services/account-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - app-network

  product-service:
    build:
      context: ../../services/product-service
      target: development
    env_file:
      - ../../services/product-service/.env
    ports:
      - "3002:3002"
    volumes:
      - ../../services/product-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - app-network

  frontend-react:
    build:
      context: ../../services/frontend-react
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ../../services/frontend-react:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  mongo:
    image: mongo:7.0
    command: ["mongod","--quiet","--logpath","/dev/null"]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express:1.0.2-20
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
  mongo-data: