services:
  api-gateway:
    build:
      context: ../../services/api-gateway
      target: production
    ports:
      - "18000:8000"
    networks:
      - app-network
    restart: unless-stopped

  account-service:
    build:
      context: ../../services/account-service
      target: production
    env_file:
      - ../../services/account-service/.env
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  product-service:
    build:
      context: ../../services/product-service
      target: production
    env_file:
      - ../../services/product-service/.env
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped

  frontend-react:
    build:
      context: ../../services/frontend-react
      target: production
    ports:
      - "18080:80"
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    command: ["mongod","--quiet","--logpath","/dev/null"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1.0.2-20
    ports:
      - "18081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: password
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:

volumes:
  postgres-data:
  mongo-data: