services:
  frontend-react:
    build:
      context: ../../services/frontend-react
      dockerfile: Dockerfile 
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped

  api-gateway:
    build:
      context: ../../services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: unless-stopped

  account-service:
    build:
      context: ../../services/account-service
      dockerfile: Dockerfile
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge