services:
  backend-api:
    command: npm run dev
    volumes:
      - ../../services/backend-api:/usr/src/app
      - /usr/src/app/node_modules

  frontend-react:
    build:
      context: ../../services/frontend-react
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../../services/frontend-react:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - WDS_SOCKET_HOST=0.0.0.0
      - WDS_SOCKET_PORT=0
      - CHOKIDAR_USEPOLLING=true