services:
  api-gateway: 
    build:
      context: ../../services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  user-service:
    build:
      context: ../../services/user-service
      dockerfile: Dockerfile
    networks:
      - app-network

  frontend-react:
    build:
      context: ../../services/frontend-react
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api-gateway
    networks:
      - app-network

networks:
  app-network:
    driver: bridge